### ISSUE TITLE
EACopy 2 times slower than robocopy when copying to empty destination

### ISSUE THREAD

**Issue by marcinbarczynski** [electronicarts/EACopy#9]
I compared the performance of EACopy v1.12 and Robocopy on Windows 10 when copying locally 1GB in 10K files (100 files per dir). Here is the code:
```powershell
$total_bytes = 1000000000
$dirs_cnt = 100
$files_per_dir_cnt = 100

$source = "C:\tmp\sync-test\src"
$destination = "C:\tmp\sync-test\dst"

$cmds = @(
  "robocopy.exe $source $destination /E /NDL /NFL /NP",
  ".\EACopy.exe $source $destination /E /LOGMIN",
  ".\EACopy.exe $source $destination /E /LOGMIN /SYSTEMCOPY"
)

function Prepare-Tree {
  New-Item -ItemType "directory" -Path "$source" | Out-Null
  $contents = "0" * ($total_bytes / $dirs_cnt / $files_per_dir_cnt)
  for ($idx = 1; $idx -le $dirs_cnt; $idx++) {
    New-Item -ItemType "directory" -Path "$source\dir-$idx" | Out-Null
    for ($jdx = 1; $jdx -le $files_per_dir_cnt; $jdx++) {
      New-Item -ItemType "file" -Path "$source\dir-$idx\file-$jdx" -Value $contents | Out-Null
    }
  }
  New-Item -ItemType "directory" -Path "$destination" | Out-Null
}


Remove-Item $source -Recurse -Force
Remove-Item $destination -Recurse -Force
foreach ($cmd in $cmds) {
  Prepare-Tree	
  echo $cmd
  Measure-Command { Invoke-Expression $cmd }
  Remove-Item $source -Recurse
  Remove-Item $destination -Recurse
}
```
The results showed that EACopy is at least 2 times slower than Robocopy. 
```
Robocopy: 6.45s
EACopy: 12.75s
EACopy /SYSTEMCOPY: 17.00s
```

Interestingly, when copying 10K empty files (`$total_bytes = 0`), EACopy is faster. Here are the results:
```
Robocopy: 4.23s
EACopy: 2.67s
EACopy /SYSTEMCOPY: 3.22s
```
I obtained similar results on a couple of machines.

Why is EACopy slower when copying non-empty files?

**Comment by honkstar1** [comment]
Very strange, I ran your test on my machine too. I'm surprised my copying is so much slower than your numbers given that I have a quite powerful computer (i9-1980XE with NVMe Samsung 970). There is a ton of antivirus/security running on our computers so, who knows :-)

Robocopy: 23.95 seconds
EACopy: 20.74 seconds
EACopy /SYSTEM: 19.82 seconds

This is a very simple test and since you are copying to an empty folder EACopy takes note of that and skip a bunch of overhead. I'm having a hard time seeing any of the three alternatives being faster than the other... especially EACopy /SYSTEM vs Robocopy.. they should very likely be the same.

For fun I also tested with /MT:16 in your script and my timings were

Robocopy: 4.96 seconds
EACopy: 1.86 seconds
EACopy /SYSTEM 1.94 seconds

Has any of those machines you tested have antivirus etc on them? What about exclusion rules etc?.

According to Ned Pyle @ microsoft, Robocopy uses the system functions "CopyFile" to copy.. so with /SYSTEM copy-times should(TM) be more or less identical independent of file size. The difference could be in finding the files but since you showed in your test that empty files were faster I have no answer for you :-)

If you come to think of anything, please tell me.. I'm curious since I've only seen Robocopy being faster in scenarios where odx is enabled and server is of certain brands (which makes me suspect they are doing something more than just call "CopyFile").

**Comment by marcinbarczynski** [comment]
Thanks for the quick reply. 

I looked into it, and discovered that Windows Defender Real-Time Protection and file size are key factors. There is no 3rd-party monitoring software installed on my machines.

With enabled real-time protection:
- `EACopy /SYSTEMCOPY` gets slower when file size exceeds 4KB
- `EACopy` gets slower when file size exceeds 8 KB:

```
file size: 4096 (1 dir, 10K files)

robocopy: 6.04s
eacopy: 4.21s
eacopy /SYSTEMCOPY: 4.95s


file size: 4097 (1 dir, 10K files)

robocopy: 6.06s
eacopy: 4.34s
eacopy /SYSTEMCOPY: 16.44s



file size: 8192 (1 dir, 10K files)

robocopy: 5.98s
eacopy: 4.19s
eacopy /SYSTEMCOPY: 16.36s


file size: 8193 (1 dir, 10K files)

robocopy: 6.41s
eacopy: 12.79s
eacopy /SYSTEMCOPY: 16.48s
```

After disabling real-time protection, EACopy is faster than robocopy:
```
file size: 8193 (1 dir, 10K files)

robocopy: 5.27s
eacopy: 4.01s
eacopy /SYSTEMCOPY: 4.82s
```

This raises two questions:
1. Where do the thresholds come from? 
Cluster size is 4KB, so they're exactly one and two clusters. Initially, I thought that maybe resident files come into play, but they are limited to MFT entry size which is 1KB.

2. Why does enabling real-time protection has smaller impact on robocopy?


That's very interesting. I wonder if you have any intuition where to dig in?

**Comment by honkstar1** [comment]
That is indeed very interesting data. I wonder if Windows Defender has built-in exclusion rules on robocopy or something. Tbh I haven't really looked much at copying from local drive to local drive. I want it to be fast ofc, but our bottlenecks are elsewhere :-) So if you figure something out, please share.

Here's a funny experiment. Copy and rename EACopy to robocopy in the location robocopy exist in, and run again. Hopefully (for microsoft's sake) you will see the same results, but if not, that would be hilarious :-)

Regarding your question number 1. That doesn't make sense at all, lol. Since ms claims robocopy uses "CopyFile" (https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfileexa) and eacopy /SYSTEMCOPY is doing the exact same I can't see how they can have different performance.. unless they give robocopy special treatment (which your windows defender experiment implies)

For fun, can you test /MT:16 or something on your computer and see if the relationship between eacopy and robocopy stays the same.
